# Generated by Django 4.0.3 on 2022-06-15 00:34

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='image',
            field=models.ImageField(default='placeholder.jpg', upload_to=products.models.Producer.image_path),
        ),
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(default='placeholder.jpg', upload_to=products.models.Brand.image_path),
        ),
    ]
