# Generated by Django 4.0.6 on 2022-08-24 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_comment_text_alter_review_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='avg_score',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=4, null=True),
        ),
    ]
