# Generated by Django 4.0.3 on 2022-04-21 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0004_commentreaction_reviewreaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_reactions', to=settings.AUTH_USER_MODEL)),
                ('comment', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='products.comment')),
                ('review', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='products.review')),
            ],
        ),
        migrations.RemoveField(
            model_name='reviewreaction',
            name='author',
        ),
        migrations.RemoveField(
            model_name='reviewreaction',
            name='review',
        ),
        migrations.DeleteModel(
            name='CommentReaction',
        ),
        migrations.DeleteModel(
            name='ReviewReaction',
        ),
    ]
