# Generated by Django 4.0.6 on 2022-08-24 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_review_count_product_score_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='review_count',
            new_name='reviews_count',
        ),
    ]
