# Generated by Django 4.0.6 on 2022-08-26 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_review_count_product_reviews_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='avg_score',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='reviews_count',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='score_count',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='producer',
            name='avg_score',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='producer',
            name='reviews_count',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='producer',
            name='score_count',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
