# Generated by Django 4.0.3 on 2022-04-30 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_reaction_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reaction',
            name='comment',
        ),
    ]
