# Generated by Django 4.0.3 on 2022-04-30 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_reaction_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='products.review'),
        ),
    ]
