# Generated by Django 4.0.6 on 2022-08-26 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_brand_avg_score_alter_brand_reviews_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.IntegerField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='short_desc',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='vg',
            field=models.IntegerField(default=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='volume',
            field=models.ForeignKey(default=70, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.volume'),
            preserve_default=False,
        ),
    ]
