# Generated by Django 4.0.3 on 2022-05-04 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_review_dislikes_review_likes'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reaction',
            constraint=models.UniqueConstraint(fields=('author', 'review'), name='unique_reaction'),
        ),
    ]
