# Generated by Django 4.0.5 on 2022-07-14 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bookmark',
            constraint=models.UniqueConstraint(fields=('author', 'product'), name='unique_bookmark'),
        ),
    ]
