# Generated by Django 4.0.6 on 2022-08-30 19:47

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_product_volume_product_volume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='short_desc',
        ),
        migrations.AddField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(default='placeholder.jpg', upload_to=products.models.Product.thumbnail_path),
        ),
    ]
