# Generated by Django 4.0.6 on 2022-07-29 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_bookmark_unique_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mail',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
