# Generated by Django 4.0.6 on 2022-09-04 12:21

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_product_short_desc_product_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='thumbnail',
            field=models.ImageField(default='placeholder.jpg', upload_to=products.models.Brand.thumbnail_path),
        ),
        migrations.AddField(
            model_name='producer',
            name='thumbnail',
            field=models.ImageField(default='placeholder.jpg', upload_to=products.models.Producer.thumbnail_path),
        ),
    ]
