# Generated by Django 4.0.6 on 2022-07-29 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_profile_mail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='mail',
        ),
    ]
