# Generated by Django 4.0.6 on 2022-08-02 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_review_options_remove_profile_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['id']},
        ),
    ]
