# Generated by Django 4.0.6 on 2022-09-20 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producer',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producers', to='products.country'),
        ),
    ]
