# Generated by Django 4.0.6 on 2022-09-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_producer_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='ig',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producer',
            name='tg',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producer',
            name='vk',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producer',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
