# Generated by Django 4.0.6 on 2022-10-11 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_brand_is_salt_brand_nic_content_brand_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='nic_content',
            field=models.ManyToManyField(blank=True, related_name='brands', to='products.nicotine'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='volume',
            field=models.ManyToManyField(blank=True, related_name='brands', to='products.volume'),
        ),
    ]
