# Generated by Django 4.0.6 on 2022-10-11 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_brand_nic_content_alter_brand_volume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_salt',
        ),
        migrations.RemoveField(
            model_name='product',
            name='nic_content',
        ),
        migrations.RemoveField(
            model_name='product',
            name='volume',
        ),
    ]
