# Generated by Django 4.0.6 on 2023-05-21 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_brand_vg_product_nic_content_product_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='flavors',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.flavor'),
        ),
        migrations.AlterField(
            model_name='product',
            name='vg',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
