# Generated by Django 4.0.6 on 2023-06-26 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_alter_producer_slug_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
