# Generated by Django 4.0.6 on 2023-07-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_suggestion_product_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suggestion',
            options={'ordering': ['processed', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='suggestion',
            name='product_url',
        ),
        migrations.AddField(
            model_name='suggestion',
            name='product_slug',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
