# Generated by Django 4.0.6 on 2023-07-10 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_device_review_devices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='avg_score',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='producer',
            name='avg_score',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='product',
            name='avg_score',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='review',
            name='devices',
            field=models.ManyToManyField(related_name='reviews', to='products.device'),
        ),
    ]
