# Generated by Django 4.0.6 on 2023-07-11 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_alter_brand_avg_score_alter_producer_avg_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='devices',
            field=models.ManyToManyField(blank=True, related_name='reviews', to='products.device'),
        ),
    ]
