# Generated by Django 4.0.6 on 2023-09-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_alter_review_devices'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='devices',
            field=models.ManyToManyField(blank=True, related_name='suggestion', to='products.device'),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='nic_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
