# Generated by Django 4.0.6 on 2023-09-27 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_suggestion_devices_suggestion_nic_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='nic_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
